name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Docker Login
      run: docker login -u ${{ secrets.USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.USER }}/task-manager-api:latest .
        docker push ${{ secrets.USER }}/task-manager-api:latest